name: MCUs Development Environment Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build
      run: docker build -t dev-environments-mcus ./docker
    - name: Tags
      run: |
        docker tag dev-environments-mcus ${{ secrets.DOCKER_HUB_USER }}/dev-environments-mcus:${{ github.sha }}
        docker tag dev-environments-mcus ${{ secrets.DOCKER_HUB_USER }}/dev-environments-mcus:latest
    - name: Push
      run: |
        docker push ${{ secrets.DOCKER_HUB_USER }}/dev-environments-mcus:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USER }}/dev-environments-mcus:latest

